baseURL = "https://wb-data-lab.netlify.app"
languageCode = "en-us"
title = "World Bank Data Lab"
assetDir = "static/assets"

[params]
	dataResourcesLinkTitle = "Find WB Data Resources"
	dataResourcesLink = "/data-resources-directory"

	externalPartnershipsLinkTitle = "Find External Collaborators"

	dataPartnershipsLinkTitle = "Data Partnerships"
	dataPartnershipsLink = "https://datapartnership.org"

	digitalLiteracyLinkTitle = "Expand Your Digital Literacy"

	aboutLinkTitle = "About" 
	aboutPageLink = "/about"
	
	workshopsSectionLabel = "Workshops & Clinics"
	workshopsLink = "/workshops-and-clinics"

	dataDirectoryLabel = "Find World Bank Data Resources"	

	dataLeadsLabel = "Data Lab Leads"	
	dataLeadsLink = "/data-leads"


	universityDataFellowsLabel = "University Data Fellows"	
	universityDataFellowsLink = "/university-data-fellows"

[module]
	[hugoVersion]
	extended = true

[taxonomies]
	workshop_types = "workshop_types"
	teams = "teams"