baseURL = "http://example.org/"
languageCode = "en-us"
title = "World Bank Data Lab"
assetDir = "static/assets"

[params]
	internalCollabLinkTitle = "Internal Collaboration"
	partnershipsLinkTitle = "External Partnerships"
	dataPartnershipsLinkTitle = "Data Partnerships"
	staffCapacityLinkTitle = "Staff Capacity Building"
	aboutLinkTitle = "About" 

	labLeadsCount = 205
	peopleTrainedCount = 205
	connectionsCount = 394
	projectsCount = 105
	
[module]
	[hugoVersion]
	extended = true

[taxonomies]
	workshop_types = "workshop_types"
	teams = "teams"